---
title: "Final Project!"
author: "Rachel Wells"
date: "4/27/2020"
output: pdf_document
---


# Research Question 1 


```{r}
policekillings<-read.csv("C:\\Users\\Rachel Wells\\Desktop\\Stat 1601\\PoliceKillings.csv")
```


```{r}
policekillings1<-na.omit(policekillings)
```


```{r}
library(ggplot2)
ggplot(policekillings1, mapping = aes(x = college , y = urate)) + 
  geom_point(color="orange")+geom_smooth(method="lm")+labs(x = "Share of 25 Plus Population with a COllege Degree", y="Tract-level Unemployment Rate",
       title = "The Effect of Degree on Unemployment Rate") 

```


```{r}
uratecol<-lm(urate~college,data=policekillings1)
summary(uratecol)
```


```{r}

cor(policekillings1$urate, policekillings1$college)
```


```{r}
uratecol<-lm(urate~college,data=policekillings1)
new_uratecol<-data.frame(college=0.3)
predict(uratecol,new_uratecol)
```


# Research Question 2 
```{r}
policekillings<-read.csv("C:\\Users\\Rachel Wells\\Desktop\\Stat 1601\\PoliceKillings.csv")
Police_Killings<-policekillings[-c(13,451,452,453),]
age_1=Police_Killings$age 
age_2<-c(age_1) 
t.test(age_2,conf.level = 0.95)
```

```{r}
t.test(age_2,mu=30,alternative="less")
```

```{r}
library(ggplot2)
ggplot(Police_Killings,aes(y=age_2))+geom_boxplot(color="blue")+labs(y="Ages",title="Age Differences")
```

# Research Question 3 
```{r}
policekillings<-read.csv("C:\\Users\\Rachel Wells\\Desktop\\Stat 1601\\PoliceKillings.csv")
library(dplyr)
table(policekillings%>%select(raceethnicity))
blackunarmed=policekillings%>%filter(raceethnicity=="Black"&armed=="No")
whiteunarmed=policekillings%>%filter(raceethnicity=="White"&armed=="No")
```
```{r}
nrow(blackunarmed)
nrow(whiteunarmed)
```
```{r}
whiteandblack=policekillings%>%filter(raceethnicity=="Black"|raceethnicity=="White")
library(ggplot2)
ggplot(whiteandblack,aes(x=raceethnicity,fill=armed))+geom_bar()+labs(x="Race",y="Killed")+
    geom_text(aes(label=..count..),stat="count",position=position_stack(.5))
```
```{r}
prop.test(c(32,51),c(135,236),alternative = "greater")
```
```{r}

library(dplyr)
policemodel=lm(county_income~urate+college,policekillings)
```

# Research Question 4 

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data<-read.csv("C:\\Users\\Rachel Wells\\Desktop\\Stat 1601\\PoliceKillings.csv")
names(data)

library(dplyr)
library(ggplot2)

race <- factor(data$raceethnicity, levels = c('Asian', 'Black', 'Hispanic',
                                              'Native American', 'Unknown', 'White'))

#remove Unknown
race2 <- factor(data$raceethnicity, levels = c('Asian', 'Black', 'Hispanic',
                                               'Native American', 'White'))
```

```{r}
table(race2)
chisq.test(table(race2))
chisq.test(table(race2), p = c(1/5,1/5,1/5,1/5,1/5))
```

```{r}
racedf = data.frame(race2)
ggplot(data = racedf, aes(x = data$race)) + 
  labs(x = 'Race', y = 'Count') + geom_bar()
```

